name: communityfor1024
description: 草榴社区非官方客户端

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^3.0.9
  dio_cookie_manager: 1.0.0
  html: ^0.14.0+3
  fast_gbk: ^0.1.2+1
  path_provider: ^1.6.5
  sqflite: ^1.1.6+4
  fluro: ^1.6.2
  flutter_widget_from_html_core: ^0.3.2+2
  flutter_easyrefresh: ^2.1.0
  url_launcher: ^5.4.2
  cached_network_image: ^2.0.0
  flutter_slidable: ^0.5.4
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  flutter_spinkit: ^4.1.2+1
  oktoast: ^2.3.1+1
  crypto: ^2.1.3
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
