name: communityfor1024
description: 草榴社区非官方客户端

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^3.0.4
  dio_cookie_manager: 1.0.0
  html: ^0.14.0+2
  fast_gbk: ^0.1.1+1
  path_provider: ^1.3.0
  sqflite: ^1.1.6+4
  fluro: ^1.5.1
  flutter_widget_from_html: ^0.3.2+2
  extended_nested_scroll_view: ^0.3.8
  flutter_easyrefresh: ^2.0.4
  url_launcher: ^5.1.2
  cached_network_image: ^2.0.0
  flutter_slidable: ^0.5.4
  provider: ^3.1.0
  flutter_spinkit: ^4.0.0
  oktoast: ^2.2.0
  identicon: ^0.1.1
  crypto: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
